version: '3'
services:
  api:
    build:
      context: .
    ports:
      - 9000:9000
    command: npm start
 
  test:
    build:
      context: .
    environment:
      - CI=true
    command: npm test
